#!/usr/bin/env sh
node scripts/validate-commit.mjs "$1"

# Skip tests for merge, fixup, and squash commits
commit_msg=$(cat "$1")
case "$commit_msg" in
  Merge\ *|fixup\!*|squash\!* )
    exit 0
    ;;
esac

npm test
